The commands git, curl, tmux and zsh must exist.

diff --git a/.bin/insta-dot b/.bin/insta-dot
--- a/.bin/insta-dot
+++ b/.bin/insta-dot
@@ -1,17 +1,18 @@
-#!/bin/bash
 
 set -e errexit
 set -o nounset
 
-if ! [ -x "$(command -v git)" ]; then
-    echo 'Error: git is not installed.' >&2
-    exit 1
-fi
+function command_exist {
+    if ! [ -x "$(command -v $1)" ]; then
+        echo "Error: '$1' is not installed." >&2
+        exit 1
+    fi
+}
 
-if ! [ -x "$(command -v curl)" ]; then
-    echo 'Error: git is not installed.' >&2
-    exit 1
-fi
+command_exist git
+command_exist curl
+command_exist tmux
+command_exist zsh
 
 cd $HOME
 
